# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nodus 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "nodus"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Joseph Wecker"]
  s.date = "2014-06-26"
  s.description = "EXPERIMENTAL. A form of data-flow programming based loosely on Kahn Process Networks. Will allow for setting up operational components that can be pipelined together in a graph. Assumes all components (nodes) are 'online' algorithms with more or less steady-state resource utilization for continuous streams of data."
  s.email = "joseph.wecker@exsig.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "LICENSE.txt",
    "OPERUM.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/VERSION",
    "lib/extensions.rb",
    "lib/nodus.rb",
    "lib/nodus/version.rb",
    "nodus.gemspec",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/exsig/nodus"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Something between a Kahn Process Network and Algorithmic Skeleton for parallel pipelining and signal processing"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 4.1.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<brice>, [">= 0"])
      s.add_development_dependency(%q<ansi>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<ffaker>, [">= 0"])
      s.add_development_dependency(%q<randexp>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 5.3"])
      s.add_development_dependency(%q<minitest-reporters>, [">= 1.0.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.7.1"])
    else
      s.add_dependency(%q<activesupport>, [">= 4.1.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<brice>, [">= 0"])
      s.add_dependency(%q<ansi>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<ffaker>, [">= 0"])
      s.add_dependency(%q<randexp>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 5.3"])
      s.add_dependency(%q<minitest-reporters>, [">= 1.0.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.7.1"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 4.1.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<brice>, [">= 0"])
    s.add_dependency(%q<ansi>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<ffaker>, [">= 0"])
    s.add_dependency(%q<randexp>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 5.3"])
    s.add_dependency(%q<minitest-reporters>, [">= 1.0.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.7.1"])
  end
end

